# Generated by Django 2.1.1 on 2020-01-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200114_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'обзор', 'verbose_name_plural': 'обзоры'},
        ),
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Car', verbose_name='автомобиль'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='текст обзора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, verbose_name='заголовок статьи'),
        ),
    ]
